# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-04 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
